name: CI
  on:
    push:
    pull__request:

perfmission:
  contents: read
  pull -requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-versiyon: "3.12"

      - name: install pytest
        run: pip install pytest

      - name: Run tests
        run: pytests

